### ISSUE TITLE
Change repo name to takeaburgerleaveaburger

### ISSUE THREAD

**Issue by deepfriedfilth** [avstjohn/takeaburgerleaveaburger#1]
I don't _think I_ have access to do so myself, otherwise, it'd already be done.

**Comment by avstjohn** [comment]
All who vote, "Ye"?

**Comment by deepfriedfilth** [comment]
![](https://media0.giphy.com/media/zMCfqXkwjmTO8/giphy.gif)

**Comment by avstjohn** [comment]
You saw exactly where I was going with this.

**Comment by avstjohn** [comment]
Guess we have our subject matter: burgers.

**Comment by avstjohn** [comment]
![image](https://user-images.githubusercontent.com/24692437/49838412-2a248100-fd70-11e8-8776-100f4bef7fe8.png)

**Comment by avstjohn** [comment]
<iframe src="https://giphy.com/embed/8yJ7D1ARiZ4Zi" width="480" height="270" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/burger-8yJ7D1ARiZ4Zi">via GIPHY</a></p>

**Comment by deepfriedfilth** [comment]
Ahem.. 👉🏼 https://addons.mozilla.org/en-US/firefox/addon/gifs-for-github/

**Comment by avstjohn** [comment]
Ahahha, saw there was a Chrome extension, and didn't bother looking for Firefox. Need a gosh darn extension for everything!

![](https://media1.giphy.com/media/2Faz6BO8sFxaCrtew/giphy.gif)

**Comment by deepfriedfilth** [comment]
that, or trudging thru opening a new tab, searching giphy yourself, clicking embed, making sure it's the gif version, copying it to your clipboard, returning to the original tab, and then trying to remember obscure markdown syntax, which is `![](url-of-gif-file-here.gif)` by the way. best off with the extension, methinks. keeps it all concise!

we don't want #workhardernotsmarter to become synonymous with #takeaburgerleaveaburger now 💩

**Comment by avstjohn** [comment]
True that. Someone worked hard to abstract all that away! The extension taught me the markdown at least.
